
services:
  db_mysql:
    container_name: mysql_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
      MYSQL_USER: devkiki
      MYSQL_PASSWORD: devkiki77
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

